/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.50).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Error;
import io.swagger.model.Game;
import io.swagger.model.GameShop;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.security.Principal;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-11-09T20:37:50.498499694Z[GMT]")
@Validated
public interface GsApi {

    @Operation(summary = "Добавить доступ", description = "", tags={ "gs" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "100", description = "Error", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "200", description = "Успех", content = @Content(mediaType = "application/json", schema = @Schema(implementation = GameShop.class))) })
    @RequestMapping(value = "/gs",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Game> createGame(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Game body , @AuthenticationPrincipal Principal principal);


    @Operation(summary = "удаление", description = "", tags={ "gs" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "100", description = "Error", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "200", description = "Успех") })
    @RequestMapping(value = "/gs/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> delGame(@Parameter(in = ParameterIn.PATH, description = "Id of Game", required=true, schema=@Schema()) @PathVariable("id") int id , @AuthenticationPrincipal Principal principal);


    @Operation(summary = "получить Инфу", description = "", tags={ "gs" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "100", description = "Error", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "200", description = "Успех", content = @Content(mediaType = "application/json", schema = @Schema(implementation = GameShop.class))) })
    @RequestMapping(value = "/gs",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<GameShop> getGs();


    @Operation(summary = "по id", description = "", tags={ "gs" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "100", description = "Error", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))),
        
        @ApiResponse(responseCode = "200", description = "Успех", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Game.class))) })
    @RequestMapping(value = "/gs/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Game> getGameById(@Parameter(in = ParameterIn.PATH, description = "Id of game", required=true, schema=@Schema()) @PathVariable("id") Integer id);

}

